apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  selector:
    app: eureka-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: proveedor-service
  labels:
    app: proveedor-service
spec:
  selector:
    app: proveedor-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: acopio-service
  labels:
    app: acopio-service
spec:
  selector:
    app: acopio-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: datos-service
  labels:
    app: datos-service
spec:
  selector:
    app: datos-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: planilla-service
  labels:
    app: planilla-service
spec:
  selector:
    app: planilla-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080