apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "tingesopep2"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "1234"
          volumeMounts:
            - name: tingesopep2-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: tingesopep2-persistent-storage
          persistentVolumeClaim:
            claimName: tingesopep2-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tingesopep2-pv-claim
  labels:
    app: tingesopep2
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tingesopep2
data:
  name: "tingesopep2"

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432