apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service
          image: fernandoper501/pep2_eureka_service:latest
          ports:
            - containerPort: 8761
          env:
            - name: spring.cloud.config.uri
              value: http://config-service:8081
            - name: spring.config.import
              value: optional:configserver:http://config-service:8081
